name: CI Hospital Management

on: [push, pull_request] # Se ejecuta en push y pull request 

permissions:
  contents: write  # Necesario para subir el badge dinámico 
  checks: write    # Necesario para el informe de resultados 
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar permisos al Wrapper
        run: chmod +x mvnw # Requisito explícito del enunciado 

      - name: Compile proyecto
        run: ./mvnw compile --no-transfer-progress # Requisito del enunciado 

      - name: Ejecutar Tests de Integracion
        # Ejecuta verify y genera el reporte para Jacoco 
        run: ./mvnw verify jacoco:report --no-transfer-progress --batch-mode

      - name: Generar Informe de Resultados (Reporter)
        if: always() # Para que el reporte aparezca aunque fallen los tests 
        uses: dorny/test-reporter@v1 
        with:
          name: Informe de Pruebas de Integracion
          path: 'target/failsafe-reports/*.xml'
          reporter: java-junit

      - name: Generar Badge de Cobertura (Jacoco)
        if: always() && github.event_name != 'pull_request'
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2 
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: .github/badges

      - name: Commit y Push del badge dinamico
        if: always() && github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/*.svg
          git commit -m "Autodocumentacion: Actualizar badge de cobertura" || exit 0
          git push